const theme = Object.freeze({
  // font
  fontUrl: 'https://media.bringweb3.io/fonts/px-grotesk-regular.css',
  fontFamily:
    '"PxGrotesk", system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Open Sans", "Helvetica Neue", sans-serif',
  // Popup
  popupBg: '#000',
  popupShadow:
    '0px 6px 20px 0px rgba(0, 0, 0, 0.10), 0px 1px 8px 0px rgba(0, 0, 0, 0.06)',
  xBtnFC: '#E1E6F5',
  // Primary button
  primaryBtnBg: '#00DB7D',
  primaryBtnFS: '17px',
  primaryBtnFW: '700',
  primaryBtnFC: '#171717',
  primaryBtnBorderC: 'transparent',
  primaryBtnBorderW: '0',
  primaryBtnRadius: '5px',
  // Secondary button
  secondaryBtnBg: 'transparent',
  secondaryBtnFS: '15px',
  secondaryBtnFW: '700',
  secondaryBtnFC: '#00DB7D',
  secondaryBtnBorderC: '#00DB7D',
  secondaryBtnBorderW: '2px',
  secondaryBtnRadius: '5px',
  // Markdown
  markdownBg: '#000',
  markdownFS: '14px',
  markdownFW: '400',
  markdownFC: '#FBFBFB',
  markdownTitleFS: '14px',
  markdownTitleFW: '700',
  markdownTitleFC: '#FBFBFB',
  markdownBorderW: '1px',
  markdownRadius: '5px',
  markdownBorderC: '#6F6F6F',
  markdownScrollbarC: '#7F7F7F',
  // Wallet address
  walletBg: '#222',
  walletFS: '13px',
  walletFW: '400',
  walletFC: '#EFEFEF',
  walletBorderC: 'transparent',
  walletBorderW: '0',
  walletRadius: '3px',
  // Details of offering
  detailsBg: '#222',
  detailsTitleFS: '17px',
  detailsTitleFW: '400',
  detailsTitleFC: '#FBFBFB',
  detailsSubtitleFS: '17px',
  detailsSubtitleFW: '400',
  detailsSubtitleFC: '#FBFBFB',
  detailsRadius: '8px',
  detailsBorderW: '0',
  detailsBorderC: 'transparent',
  detailsAmountFC: '#00F58C',
  detailsAmountFW: '400',
  // Logo
  logoBg: 'white',
  logoRadius: '50%',
  logoTxtFS: '15px',
  logoTxtFW: '400',
  logoTxtFC: '#FBFBFB',
  // Overlay
  overlayWaitingBg: '#15171F',
  overlayBg: '#1F232ECC',
  overlayFS: '17px',
  overlayFW: '400',
  overlayFC: '#FBFBFB',
  loaderBg: '#00F58C',
  // Optout \ Turn off
  optoutBg: '#222',
  optoutFS: '21px',
  optoutFW: '700',
  optoutFC: '#FBFBFB',
  optoutRadius: '8px',
  optoutDescFS: '16px',
  optoutDescFW: '400',
  optoutDescFC: '#FBFBFB',
  labelFS: '16px',
  labelFW: '400',
  labelFC: '#FBFBFB',
  labelDescFS: '16px',
  labelDescFW: '700',
  labelDescFC: '#FBFBFB',
  // X Button and close buttons
  closeFS: '15px',
  closeFW: '400',
  closeFC: '#FBFBFB',
  // Token name
  tokenBg: '#222',
  tokenFS: '14px',
  tokenFW: '500',
  tokenFC: '#00DB7D',
  tokenBorderW: '0',
  tokenBorderC: 'transparent',
  tokenRadius: '80px',
  // Clarify text
  clarifyFS: '15px',
  clarifyFW: '400',
  clarifyFC: '#FBFBFB',
  // Notification popup
  notificationFS: '16px',
  notificationFW: '400',
  notificationFC: '#FFF',
  notificationBtnBg: '#00DB7D',
  notificationBtnFS: '16px',
  notificationBtnFW: '700',
  notificationBtnFC: '#222',
  notificationBtnBorderW: '0',
  notificationBtnBorderC: 'transparent',
  notificationBtnRadius: '5px',
  // Activate title
  activateTitleFS: '21px',
  activateTitleFW: '700',
  activateTitleFC: '#FBFBFB',
  activateSubtitleFS: '15px',
  activateSubtitleFW: '400',
  activateSubtitleFC: '#FBFBFB',
  activateWalletNameFS: '13px',
  activateWalletNameFW: '400',
  activateWalletNameFC: '#00DB7D',
});

export default theme;
